# This is a basic workflow to help you get started with Actions

name: TestAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

       # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make cmake

      # Install norminette (version 3.3.51)
      - name: Install norminette
        run: |
          pip install norminette==3.3.51

      # Validate files with norminette
      - name: Validate code with norminette
        run: norminette -Ra src

      # Runs a set of commands using the runners shell
      - name: Run own tests
        run: make tests
